server.port = 8083


spring.datasource.url=jdbc:postgresql://ep-fragrant-bonus-adkrc2lo.c-2.us-east-1.aws.neon.tech/Opaque_security?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UaWG7D9uygBN
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

admin.default.username=admin
admin.default.password=admin

jwt.signing-secret = secret123
